---
title: "Titre de votre page d'exploration"
title-block-banner: false
description: | 
  Petite description de cette page.
# à changer
date: "2022-12-20"
# Modifier les détails que vous voulez
author:
  - name: "Abdoul Dramane TONDE"
    # Votre site web perso ou github
    url: https://github.com/Dramane98
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: true
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(fs)
library(lubridate)
library(tidyverse)
library(skimr)
library(countrycode)
```

## Creation de la variable continent pour les données d'Our World in Data

```{r variable continent, warning=FALSE, message=FALSE, error=FALSE}

URL <- "https://github.com/owid/co2-data/raw/master/owid-co2-data.csv"

fname <- paste(today(),
               "owid-co2-data.csv",
               sep = "_")
base_path <- path("data", "raw")
 
fpath <- path(base_path,
              fname)  

#Le ! a été ajouté pour signifié NOT comme dans:
# Si (le fichier n'existe PAS) {
#    Exécuter cette parti de code
#    } sinon {
#    Exécuter cette partie de code
#    }
if (!file.exists(fpath)) {
    file.remove(junk)
  download.file(url = URL,
                destfile = fpath) 
  paste("Le fichier",
        fpath,
        "n'existait pas, il a donc été téléchargé à l'instant."
  )
  
} else {
  print(paste("Le fichier",
              fpath,
              "existe déjà, il ne sera pas téléchargé à nouveau.")
  )
}

data <- read_csv(fpath) 
data_tbl <- as_tibble(data)
data_tbl <- data_tbl %>%
    select(country,year,iso_code,population,gdp,co2, ends_with("per_capital"), primary_energy_consumption) %>%
           mutate(continent = countrycode(data_tbl$iso_code,
                                   "iso3c",
                                   "continent"))

missing <- data_tbl %>%
    select(country,continent) %>%
    filter(!complete.cases(.))

data_continent <- data_tbl %>%
    drop_na(continent)
data_continent <- as_tibble(data_continent)
```

## Données Extremes

```{r}

data %>%
    filter(country == "Afghanistan") %>%
    select(year, population, iso_code, cumulative_luc_co2)
```

```{r}

p2 <- ggplot(data = data,
             mapping = aes(x = country, y = population))
p2 + geom_boxplot()
```

## Evolution du ratio country/co2

```{r}

data %>%
    group_by(country, co2) %>%
    summarise(new = n()) %>%
    mutate(new1 = new / sum(new) * 100)
evolution <- group_by(.data = data, country, co2) %>%
    summarise(n = n())

evolution <- evolution %>% mutate(pourcent = n / sum(n) * 100)
```

```{r}

p3 <- ggplot(evolution, aes(x = country, y = pourcent))

p3 + geom_line()
```

## Un peu d'interactivité pour le plaisir!

```{r map, eval=FALSE}
library(leaflet)
leaflet() %>%
    setView(lng=150,
            lat=-30,
            zoom = 3) %>%
    addTiles() %>%
    addMarkers(lng=174.768,
               lat=-36.852,
               popup="Là où R est né") %>%
    addProviderTiles(providers$Esri.WorldGrayCanvas)
```

## Peut-être que ça vous inspirera!

```{r plotly, message=FALSE, warning=FALSE, eval=FALSE}
library(plotly)
library(gapminder)
df <- gapminder

fig <- df %>%
  plot_ly(
    x = ~ gdpPercap,
    y = ~ lifeExp,
    size = ~ pop,
    color = ~ continent,
    frame = ~ year,
    text = ~ country,
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    width = "100%",
    height = 600
  )

fig <- fig %>% layout(xaxis = list(type = "log"))

fig <- fig %>%
  animation_button(
    x = 0, xanchor = "left", y = -0.15, yanchor = "bottom"
  )
fig
```

------------------------------------------------------------------------

À votre imagination de jouer!
