---
title: "Page d'importation"
title-block-banner: true
description: | 
  Petite description de cette page.
# Importation de données
date: "2022-12-20"
# Modifier les détails que vous voulez
author:
  - name: "Abdoul Dramane TONDE"
    # Votre site web perso ou github
    url: https://github.com/Dramane98
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: true
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

## Telechargement des packages

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(tibble)
library(fs)
library(lubridate)
library(tidyverse)
library(skimr)
library(magrittr)
library(rvest)
library(readr)
library(tibble)
library(countrycode)
```

### Importation des données de CO2

```{r download,read, cache=TRUE}


URL <- "https://github.com/owid/co2-data/raw/master/owid-co2-data.csv"

fname <- paste(today(),
               "owid-co2-data.csv",
               sep = "_")
base_path <- path("data", "raw")
 
fpath <- path(base_path,
              fname)  

#Le ! a été ajouté pour signifié NOT comme dans:
# Si (le fichier n'existe PAS) {
#    Exécuter cette parti de code
#    } sinon {
#    Exécuter cette partie de code
#    }
if (!file.exists(fpath)) {
    file.remove(junk)
  download.file(url = URL,
                destfile = fpath) 
  paste("Le fichier",
        fpath,
        "n'existait pas, il a donc été téléchargé à l'instant."
  )
  
} else {
  print(paste("Le fichier",
              fpath,
              "existe déjà, il ne sera pas téléchargé à nouveau.")
  )
}


data <- read_csv("data/raw/2022-12-20_owid-co2-data.csv")
view(data)
skim(data)

```

V1: Le fichier a été téléchargé là:

data/raw/2022-12-20_owid-co2-data.csv

V2: V1: Le fichier a été téléchargé là: `r fpath`

### Importations des données Life Expectancy at Birth

```{r download, read, cache=TRUE, warning=FALSE, message=FALSE, error=FALSE}

URL1 <- "https://docs.google.com/spreadsheets/d/1RheSon1-q4vFc3AGyupVPH6ptEByE-VtnjOCselU0PE/edit#gid=501532268"

fname1 <- paste(today(),
               "leab-data.csv",
               sep = "_")
base_path1 <- path("data", "raw")
 
fpath1 <- path(base_path1,
              fname1)  

#Le ! a été ajouté pour signifié NOT comme dans:
# Si (le fichier n'existe PAS) {
#    Exécuter cette parti de code
#    } sinon {
#    Exécuter cette partie de code
#    }
if (!file.exists(fpath1)) {
  download.file(url = URL1,
                destfile = fpath1) 
  paste("Le fichier",
        fpath1,
        "n'existait pas, il a donc été téléchargé à l'instant."
  )
  
} else {
  print(paste("Le fichier",
              fpath1,
              "existe déjà, il ne sera pas téléchargé à nouveau.")
  )
}

data1 <- read_csv("data/raw/2022-12-20_leab-data.csv")

```

V3: Le fichier a été téléchargé là:

data/raw/2022-12-20_leab-data.csv

V4: V3: Le fichier a été téléchargé là: `r fpath1`

```{r warning=FALSE}

data_tbl <- as.tibble(data)
data1_tbl <- as.tibble(data1)
```

```{r warning=FALSE, message=FALSE, error=FALSE}

head(data)
head(data1)
```

```{r warning=FALSE, message=FALSE, error=FALSE}


```
