---
title: "Introduction"
title-block-banner: true
description: | 
  Petite description de votre projet en une ligne.
# à changer
date: "2022-12-20"
# Modifier les détails que vous voulez
author:
  - name: "Abdoul Dramane TONDE"
    # Votre site web perso ou github
    url: https://github.com/Dramane98
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: false
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

Notre projet vise à importer des données de Our World in Data et de Gapminder pour ensuite les traiter.

Premierement nous téléchargerons nos données quotidiennenment pour la base de données Our world in data par ce que ces données sont mis à jour frequemment. Ensuite pour les données des autres sources nous les téléchargerons mensuellement. Pour mieux disposer de données constament à jour nous les avons nettoyer lors de l'importation.

Pour la visualisation et les graphiques nous avons utiliser entre autre les packages ggplot et plot.

Pour l'exploitation, l'exprtation et l'analyse notre fichier exploration.qmd détaille parfaitement tout ce qu'on a eu à faire.

@owidenergy

Notre base de données de Gapminder se trouve initialement sur Rstudio. Donc nous y avons juste telecharger les données qui nous interressaient pour nos analyses. Voici l'URL qui mène directement au site web:
[Life Expectancy at Birth \| Gapminder](https://www.gapminder.org/data/documentation/gd004/)
